provides:
  - check_api

depends:
  - annotation
  - annotations

env:
  SET_VERSION_OVERRIDE: "2.3.4-$GIT_BRANCH-SNAPSHOT"
  MAVEN_OPTS: -Xmx2048

buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2
