/*
 * Copyright 2016 The Error Prone Authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source:
// third_party/java_src/error_prone/project/core/src/test/java/com/google/errorprone/bugpatterns/testdata/proto/proto_test.proto

package com.google.errorprone.bugpatterns.proto;

public final class ProtoTestInternalDescriptors {
  public static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n}third_party/java_src/error_prone/proje"
          + "ct/core/src/test/java/com/google/errorpr"
          + "one/bugpatterns/testdata/proto/proto_tes"
          + "t.proto\022!com.google.errorprone.bugpatter"
          + "ns\"`\n\025TestFieldProtoMessage\022G\n\005field\030\001 \001"
          + "(\01328.com.google.errorprone.bugpatterns.T"
          + "estFieldProtoMessage\"\314\001\n\020TestProtoMessag"
          + "e\022I\n\007message\030\001 \001(\01328.com.google.errorpro"
          + "ne.bugpatterns.TestFieldProtoMessage\022M\n\013"
          + "multi_field\030\002 \003(\01328.com.google.errorpron"
          + "e.bugpatterns.TestFieldProtoMessage\022\036\n\026t"
          + "est_field_named_count\030\003 \001(\005B)\n\'com.googl"
          + "e.errorprone.bugpatterns.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
        descriptorData,
        ProtoTestInternalDescriptors.class,
        new java.lang.String[] {},
        new java.lang.String[] {},
        assigner);
  }
}
