provides:
  - core

depends:
  - annotation
  - annotations
  - check_api
  - test_helpers
  - type_annotations

env:
  SET_VERSION_OVERRIDE: "2.5.1-$GIT_BRANCH-SNAPSHOT"
  MAVEN_OPTS: -Xmx2048m

buildResources:
  cpus: 4
  memoryMb: 4096

buildpack:
  host: git.hubteam.com
  organization: HubSpotProtected
  repository: Blazar-Buildpack-Java
  branch: v2
