maven_jar(
    name = "error_prone",
    artifact = "com.google.errorprone:error_prone_ant:2.1.2-SNAPSHOT",
    repository = "https://oss.sonatype.org/content/repositories/snapshots",
)

maven_jar(
    name = "auto_service",
    artifact = "com.google.auto.service:auto-service:1.0-rc2",
)

maven_jar(
    name = "auto_common",
    artifact = "com.google.auto:auto-common:0.3",
)

maven_jar(
    name = "guava",
    artifact = "com.google.guava:guava:19.0",
)
