# Copyright 2020 The Error Prone Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

maven_jar(
    name = "error_prone",
    artifact = "com.google.errorprone:error_prone_ant:2.4.1-SNAPSHOT",
    repository = "https://oss.sonatype.org/content/repositories/snapshots",
)

maven_jar(
    name = "auto_service",
    artifact = "com.google.auto.service:auto-service:1.0-rc2",
)

maven_jar(
    name = "auto_common",
    artifact = "com.google.auto:auto-common:0.9",
)

maven_jar(
    name = "guava",
    artifact = "com.google.guava:guava:19.0",
)
