// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MthdDcl.proto

package com.google.errorprone.bugpatterns.refactoringexperiment.models;

public final class MethodDeclaration {
  private MethodDeclaration() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MthdDclOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.MthdDcl)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string owner = 3;</code>
     */
    boolean hasOwner();
    /**
     * <code>required string owner = 3;</code>
     */
    java.lang.String getOwner();
    /**
     * <code>required string owner = 3;</code>
     */
    com.google.protobuf.ByteString
        getOwnerBytes();

    /**
     * <code>required string signature = 4;</code>
     */
    boolean hasSignature();
    /**
     * <code>required string signature = 4;</code>
     */
    java.lang.String getSignature();
    /**
     * <code>required string signature = 4;</code>
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>required string kind = 5;</code>
     */
    boolean hasKind();
    /**
     * <code>required string kind = 5;</code>
     */
    java.lang.String getKind();
    /**
     * <code>required string kind = 5;</code>
     */
    com.google.protobuf.ByteString
        getKindBytes();

    /**
     * <code>optional string return_type = 6;</code>
     */
    boolean hasReturnType();
    /**
     * <code>optional string return_type = 6;</code>
     */
    java.lang.String getReturnType();
    /**
     * <code>optional string return_type = 6;</code>
     */
    com.google.protobuf.ByteString
        getReturnTypeBytes();

    /**
     * <pre>
     * index against id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; param = 7;</code>
     */
    int getParamCount();
    /**
     * <pre>
     * index against id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; param = 7;</code>
     */
    boolean containsParam(
        int key);
    /**
     * Use {@link #getParamMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.String>
    getParam();
    /**
     * <pre>
     * index against id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; param = 7;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getParamMap();
    /**
     * <pre>
     * index against id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; param = 7;</code>
     */

    java.lang.String getParamOrDefault(
        int key,
        java.lang.String defaultValue);
    /**
     * <pre>
     * index against id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; param = 7;</code>
     */

    java.lang.String getParamOrThrow(
        int key);

    /**
     * <code>repeated string modifier = 8;</code>
     */
    java.util.List<java.lang.String>
        getModifierList();
    /**
     * <code>repeated string modifier = 8;</code>
     */
    int getModifierCount();
    /**
     * <code>repeated string modifier = 8;</code>
     */
    java.lang.String getModifier(int index);
    /**
     * <code>repeated string modifier = 8;</code>
     */
    com.google.protobuf.ByteString
        getModifierBytes(int index);

    /**
     * <code>optional string super_method_in = 9;</code>
     */
    boolean hasSuperMethodIn();
    /**
     * <code>optional string super_method_in = 9;</code>
     */
    java.lang.String getSuperMethodIn();
    /**
     * <code>optional string super_method_in = 9;</code>
     */
    com.google.protobuf.ByteString
        getSuperMethodInBytes();
  }
  /**
   * Protobuf type {@code Models.MthdDcl}
   */
  public  static final class MthdDcl extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.MthdDcl)
      MthdDclOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MthdDcl.newBuilder() to construct.
    private MthdDcl(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MthdDcl() {
      id_ = "";
      name_ = "";
      owner_ = "";
      signature_ = "";
      kind_ = "";
      returnType_ = "";
      modifier_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      superMethodIn_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MthdDcl(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              owner_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              signature_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              kind_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              returnType_ = bs;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                param_ = com.google.protobuf.MapField.newMapField(
                    ParamDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              param__ = input.readMessage(
                  ParamDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              param_.getMutableMap().put(
                  param__.getKey(), param__.getValue());
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                modifier_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000080;
              }
              modifier_.add(bs);
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              superMethodIn_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          modifier_ = modifier_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.internal_static_Models_MthdDcl_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetParam();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.internal_static_Models_MthdDcl_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl.class, com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNER_FIELD_NUMBER = 3;
    private volatile java.lang.Object owner_;
    /**
     * <code>required string owner = 3;</code>
     */
    public boolean hasOwner() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string owner = 3;</code>
     */
    public java.lang.String getOwner() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          owner_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string owner = 3;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      java.lang.Object ref = owner_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        owner_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIGNATURE_FIELD_NUMBER = 4;
    private volatile java.lang.Object signature_;
    /**
     * <code>required string signature = 4;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string signature = 4;</code>
     */
    public java.lang.String getSignature() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          signature_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string signature = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      java.lang.Object ref = signature_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KIND_FIELD_NUMBER = 5;
    private volatile java.lang.Object kind_;
    /**
     * <code>required string kind = 5;</code>
     */
    public boolean hasKind() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required string kind = 5;</code>
     */
    public java.lang.String getKind() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          kind_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string kind = 5;</code>
     */
    public com.google.protobuf.ByteString
        getKindBytes() {
      java.lang.Object ref = kind_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        kind_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RETURN_TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object returnType_;
    /**
     * <code>optional string return_type = 6;</code>
     */
    public boolean hasReturnType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string return_type = 6;</code>
     */
    public java.lang.String getReturnType() {
      java.lang.Object ref = returnType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          returnType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string return_type = 6;</code>
     */
    public com.google.protobuf.ByteString
        getReturnTypeBytes() {
      java.lang.Object ref = returnType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        returnType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAM_FIELD_NUMBER = 7;
    private static final class ParamDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.internal_static_Models_MthdDcl_ParamEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> param_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetParam() {
      if (param_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamDefaultEntryHolder.defaultEntry);
      }
      return param_;
    }

    public int getParamCount() {
      return internalGetParam().getMap().size();
    }
    /**
     * <pre>
     * index against id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; param = 7;</code>
     */

    public boolean containsParam(
        int key) {
      
      return internalGetParam().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getParam() {
      return getParamMap();
    }
    /**
     * <pre>
     * index against id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; param = 7;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.String> getParamMap() {
      return internalGetParam().getMap();
    }
    /**
     * <pre>
     * index against id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; param = 7;</code>
     */

    public java.lang.String getParamOrDefault(
        int key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetParam().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * index against id
     * </pre>
     *
     * <code>map&lt;int32, string&gt; param = 7;</code>
     */

    public java.lang.String getParamOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetParam().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int MODIFIER_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList modifier_;
    /**
     * <code>repeated string modifier = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getModifierList() {
      return modifier_;
    }
    /**
     * <code>repeated string modifier = 8;</code>
     */
    public int getModifierCount() {
      return modifier_.size();
    }
    /**
     * <code>repeated string modifier = 8;</code>
     */
    public java.lang.String getModifier(int index) {
      return modifier_.get(index);
    }
    /**
     * <code>repeated string modifier = 8;</code>
     */
    public com.google.protobuf.ByteString
        getModifierBytes(int index) {
      return modifier_.getByteString(index);
    }

    public static final int SUPER_METHOD_IN_FIELD_NUMBER = 9;
    private volatile java.lang.Object superMethodIn_;
    /**
     * <code>optional string super_method_in = 9;</code>
     */
    public boolean hasSuperMethodIn() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string super_method_in = 9;</code>
     */
    public java.lang.String getSuperMethodIn() {
      java.lang.Object ref = superMethodIn_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          superMethodIn_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string super_method_in = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSuperMethodInBytes() {
      java.lang.Object ref = superMethodIn_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        superMethodIn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOwner()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignature()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKind()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, owner_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, signature_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, kind_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, returnType_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetParam(),
          ParamDefaultEntryHolder.defaultEntry,
          7);
      for (int i = 0; i < modifier_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, modifier_.getRaw(i));
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, superMethodIn_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, owner_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, signature_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, kind_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, returnType_);
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetParam().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        param__ = ParamDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, param__);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < modifier_.size(); i++) {
          dataSize += computeStringSizeNoTag(modifier_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getModifierList().size();
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, superMethodIn_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl)) {
        return super.equals(obj);
      }
      com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl other = (com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasOwner() == other.hasOwner());
      if (hasOwner()) {
        result = result && getOwner()
            .equals(other.getOwner());
      }
      result = result && (hasSignature() == other.hasSignature());
      if (hasSignature()) {
        result = result && getSignature()
            .equals(other.getSignature());
      }
      result = result && (hasKind() == other.hasKind());
      if (hasKind()) {
        result = result && getKind()
            .equals(other.getKind());
      }
      result = result && (hasReturnType() == other.hasReturnType());
      if (hasReturnType()) {
        result = result && getReturnType()
            .equals(other.getReturnType());
      }
      result = result && internalGetParam().equals(
          other.internalGetParam());
      result = result && getModifierList()
          .equals(other.getModifierList());
      result = result && (hasSuperMethodIn() == other.hasSuperMethodIn());
      if (hasSuperMethodIn()) {
        result = result && getSuperMethodIn()
            .equals(other.getSuperMethodIn());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasOwner()) {
        hash = (37 * hash) + OWNER_FIELD_NUMBER;
        hash = (53 * hash) + getOwner().hashCode();
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      if (hasKind()) {
        hash = (37 * hash) + KIND_FIELD_NUMBER;
        hash = (53 * hash) + getKind().hashCode();
      }
      if (hasReturnType()) {
        hash = (37 * hash) + RETURN_TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getReturnType().hashCode();
      }
      if (!internalGetParam().getMap().isEmpty()) {
        hash = (37 * hash) + PARAM_FIELD_NUMBER;
        hash = (53 * hash) + internalGetParam().hashCode();
      }
      if (getModifierCount() > 0) {
        hash = (37 * hash) + MODIFIER_FIELD_NUMBER;
        hash = (53 * hash) + getModifierList().hashCode();
      }
      if (hasSuperMethodIn()) {
        hash = (37 * hash) + SUPER_METHOD_IN_FIELD_NUMBER;
        hash = (53 * hash) + getSuperMethodIn().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.MthdDcl}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.MthdDcl)
        com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDclOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.internal_static_Models_MthdDcl_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetParam();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableParam();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.internal_static_Models_MthdDcl_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl.class, com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl.Builder.class);
      }

      // Construct using MethodDeclaration.MthdDcl.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        owner_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        signature_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        kind_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        returnType_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        internalGetMutableParam().clear();
        modifier_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        superMethodIn_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.internal_static_Models_MthdDcl_descriptor;
      }

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl getDefaultInstanceForType() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl.getDefaultInstance();
      }

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl build() {
        com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl buildPartial() {
        com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl result = new com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.owner_ = owner_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.signature_ = signature_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.kind_ = kind_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.returnType_ = returnType_;
        result.param_ = internalGetParam();
        result.param_.makeImmutable();
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          modifier_ = modifier_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000080);
        }
        result.modifier_ = modifier_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000040;
        }
        result.superMethodIn_ = superMethodIn_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl) {
          return mergeFrom((com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl other) {
        if (other == com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasOwner()) {
          bitField0_ |= 0x00000004;
          owner_ = other.owner_;
          onChanged();
        }
        if (other.hasSignature()) {
          bitField0_ |= 0x00000008;
          signature_ = other.signature_;
          onChanged();
        }
        if (other.hasKind()) {
          bitField0_ |= 0x00000010;
          kind_ = other.kind_;
          onChanged();
        }
        if (other.hasReturnType()) {
          bitField0_ |= 0x00000020;
          returnType_ = other.returnType_;
          onChanged();
        }
        internalGetMutableParam().mergeFrom(
            other.internalGetParam());
        if (!other.modifier_.isEmpty()) {
          if (modifier_.isEmpty()) {
            modifier_ = other.modifier_;
            bitField0_ = (bitField0_ & ~0x00000080);
          } else {
            ensureModifierIsMutable();
            modifier_.addAll(other.modifier_);
          }
          onChanged();
        }
        if (other.hasSuperMethodIn()) {
          bitField0_ |= 0x00000100;
          superMethodIn_ = other.superMethodIn_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasOwner()) {
          return false;
        }
        if (!hasSignature()) {
          return false;
        }
        if (!hasKind()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object owner_ = "";
      /**
       * <code>required string owner = 3;</code>
       */
      public boolean hasOwner() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string owner = 3;</code>
       */
      public java.lang.String getOwner() {
        java.lang.Object ref = owner_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            owner_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string owner = 3;</code>
       */
      public com.google.protobuf.ByteString
          getOwnerBytes() {
        java.lang.Object ref = owner_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          owner_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string owner = 3;</code>
       */
      public Builder setOwner(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        owner_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string owner = 3;</code>
       */
      public Builder clearOwner() {
        bitField0_ = (bitField0_ & ~0x00000004);
        owner_ = getDefaultInstance().getOwner();
        onChanged();
        return this;
      }
      /**
       * <code>required string owner = 3;</code>
       */
      public Builder setOwnerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        owner_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object signature_ = "";
      /**
       * <code>required string signature = 4;</code>
       */
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string signature = 4;</code>
       */
      public java.lang.String getSignature() {
        java.lang.Object ref = signature_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            signature_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string signature = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        java.lang.Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string signature = 4;</code>
       */
      public Builder setSignature(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 4;</code>
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000008);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>required string signature = 4;</code>
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        signature_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object kind_ = "";
      /**
       * <code>required string kind = 5;</code>
       */
      public boolean hasKind() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required string kind = 5;</code>
       */
      public java.lang.String getKind() {
        java.lang.Object ref = kind_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            kind_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string kind = 5;</code>
       */
      public com.google.protobuf.ByteString
          getKindBytes() {
        java.lang.Object ref = kind_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          kind_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string kind = 5;</code>
       */
      public Builder setKind(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        kind_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string kind = 5;</code>
       */
      public Builder clearKind() {
        bitField0_ = (bitField0_ & ~0x00000010);
        kind_ = getDefaultInstance().getKind();
        onChanged();
        return this;
      }
      /**
       * <code>required string kind = 5;</code>
       */
      public Builder setKindBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        kind_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object returnType_ = "";
      /**
       * <code>optional string return_type = 6;</code>
       */
      public boolean hasReturnType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string return_type = 6;</code>
       */
      public java.lang.String getReturnType() {
        java.lang.Object ref = returnType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            returnType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string return_type = 6;</code>
       */
      public com.google.protobuf.ByteString
          getReturnTypeBytes() {
        java.lang.Object ref = returnType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          returnType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string return_type = 6;</code>
       */
      public Builder setReturnType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        returnType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string return_type = 6;</code>
       */
      public Builder clearReturnType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        returnType_ = getDefaultInstance().getReturnType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string return_type = 6;</code>
       */
      public Builder setReturnTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        returnType_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> param_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetParam() {
        if (param_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ParamDefaultEntryHolder.defaultEntry);
        }
        return param_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetMutableParam() {
        onChanged();;
        if (param_ == null) {
          param_ = com.google.protobuf.MapField.newMapField(
              ParamDefaultEntryHolder.defaultEntry);
        }
        if (!param_.isMutable()) {
          param_ = param_.copy();
        }
        return param_;
      }

      public int getParamCount() {
        return internalGetParam().getMap().size();
      }
      /**
       * <pre>
       * index against id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; param = 7;</code>
       */

      public boolean containsParam(
          int key) {
        
        return internalGetParam().getMap().containsKey(key);
      }
      /**
       * Use {@link #getParamMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String> getParam() {
        return getParamMap();
      }
      /**
       * <pre>
       * index against id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; param = 7;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.String> getParamMap() {
        return internalGetParam().getMap();
      }
      /**
       * <pre>
       * index against id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; param = 7;</code>
       */

      public java.lang.String getParamOrDefault(
          int key,
          java.lang.String defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetParam().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * index against id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; param = 7;</code>
       */

      public java.lang.String getParamOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetParam().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearParam() {
        internalGetMutableParam().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * index against id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; param = 7;</code>
       */

      public Builder removeParam(
          int key) {
        
        internalGetMutableParam().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String>
      getMutableParam() {
        return internalGetMutableParam().getMutableMap();
      }
      /**
       * <pre>
       * index against id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; param = 7;</code>
       */
      public Builder putParam(
          int key,
          java.lang.String value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableParam().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * index against id
       * </pre>
       *
       * <code>map&lt;int32, string&gt; param = 7;</code>
       */

      public Builder putAllParam(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        internalGetMutableParam().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.LazyStringList modifier_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureModifierIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          modifier_ = new com.google.protobuf.LazyStringArrayList(modifier_);
          bitField0_ |= 0x00000080;
         }
      }
      /**
       * <code>repeated string modifier = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getModifierList() {
        return modifier_.getUnmodifiableView();
      }
      /**
       * <code>repeated string modifier = 8;</code>
       */
      public int getModifierCount() {
        return modifier_.size();
      }
      /**
       * <code>repeated string modifier = 8;</code>
       */
      public java.lang.String getModifier(int index) {
        return modifier_.get(index);
      }
      /**
       * <code>repeated string modifier = 8;</code>
       */
      public com.google.protobuf.ByteString
          getModifierBytes(int index) {
        return modifier_.getByteString(index);
      }
      /**
       * <code>repeated string modifier = 8;</code>
       */
      public Builder setModifier(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureModifierIsMutable();
        modifier_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string modifier = 8;</code>
       */
      public Builder addModifier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureModifierIsMutable();
        modifier_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string modifier = 8;</code>
       */
      public Builder addAllModifier(
          java.lang.Iterable<java.lang.String> values) {
        ensureModifierIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, modifier_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string modifier = 8;</code>
       */
      public Builder clearModifier() {
        modifier_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string modifier = 8;</code>
       */
      public Builder addModifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureModifierIsMutable();
        modifier_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object superMethodIn_ = "";
      /**
       * <code>optional string super_method_in = 9;</code>
       */
      public boolean hasSuperMethodIn() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string super_method_in = 9;</code>
       */
      public java.lang.String getSuperMethodIn() {
        java.lang.Object ref = superMethodIn_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            superMethodIn_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string super_method_in = 9;</code>
       */
      public com.google.protobuf.ByteString
          getSuperMethodInBytes() {
        java.lang.Object ref = superMethodIn_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          superMethodIn_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string super_method_in = 9;</code>
       */
      public Builder setSuperMethodIn(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        superMethodIn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string super_method_in = 9;</code>
       */
      public Builder clearSuperMethodIn() {
        bitField0_ = (bitField0_ & ~0x00000100);
        superMethodIn_ = getDefaultInstance().getSuperMethodIn();
        onChanged();
        return this;
      }
      /**
       * <code>optional string super_method_in = 9;</code>
       */
      public Builder setSuperMethodInBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        superMethodIn_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.MthdDcl)
    }

    // @@protoc_insertion_point(class_scope:Models.MthdDcl)
    private static final com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl();
    }

    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MthdDcl>
        PARSER = new com.google.protobuf.AbstractParser<MthdDcl>() {
      public MthdDcl parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MthdDcl(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MthdDcl> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MthdDcl> getParserForType() {
      return PARSER;
    }

    public com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodDeclaration.MthdDcl getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_MthdDcl_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_MthdDcl_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_MthdDcl_ParamEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_MthdDcl_ParamEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMthdDcl.proto\022\006Models\"\354\001\n\007MthdDcl\022\n\n\002i" +
      "d\030\001 \002(\t\022\014\n\004name\030\002 \002(\t\022\r\n\005owner\030\003 \002(\t\022\021\n\t" +
      "signature\030\004 \002(\t\022\014\n\004kind\030\005 \002(\t\022\023\n\013return_" +
      "type\030\006 \001(\t\022)\n\005param\030\007 \003(\0132\032.Models.MthdD" +
      "cl.ParamEntry\022\020\n\010modifier\030\010 \003(\t\022\027\n\017super" +
      "_method_in\030\t \001(\t\032,\n\nParamEntry\022\013\n\003key\030\001 " +
      "\001(\005\022\r\n\005value\030\002 \001(\t:\0028\001BS\n>com.google.err" +
      "orprone.bugpatterns.refactoringexperimen" +
      "t.modelsB\021MethodDeclaration"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Models_MthdDcl_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_MthdDcl_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_MthdDcl_descriptor,
        new java.lang.String[] { "Id", "Name", "Owner", "Signature", "Kind", "ReturnType", "Param", "Modifier", "SuperMethodIn", });
    internal_static_Models_MthdDcl_ParamEntry_descriptor =
      internal_static_Models_MthdDcl_descriptor.getNestedTypes().get(0);
    internal_static_Models_MthdDcl_ParamEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_MthdDcl_ParamEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
