// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MthdInvc.proto

package com.google.errorprone.bugpatterns.refactoringexperiment.models;

public final class MethodInvocation {
  private MethodInvocation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MthdInvcOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.MthdInvc)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Models.Id id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional .Models.Id id = 1;</code>
     */
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getId();
    /**
     * <code>optional .Models.Id id = 1;</code>
     */
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getIdOrBuilder();

    /**
     * <pre>
     * index -&gt; arg
     * </pre>
     *
     * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
     */
    int getArgumentsCount();
    /**
     * <pre>
     * index -&gt; arg
     * </pre>
     *
     * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
     */
    boolean containsArguments(
        int key);
    /**
     * Use {@link #getArgumentsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id>
    getArguments();
    /**
     * <pre>
     * index -&gt; arg
     * </pre>
     *
     * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
     */
    java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id>
    getArgumentsMap();
    /**
     * <pre>
     * index -&gt; arg
     * </pre>
     *
     * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
     */

    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getArgumentsOrDefault(
        int key,
        com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id defaultValue);
    /**
     * <pre>
     * index -&gt; arg
     * </pre>
     *
     * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
     */

    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getArgumentsOrThrow(
        int key);

    /**
     * <code>optional .Models.Id receiver = 3;</code>
     */
    boolean hasReceiver();
    /**
     * <code>optional .Models.Id receiver = 3;</code>
     */
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getReceiver();
    /**
     * <code>optional .Models.Id receiver = 3;</code>
     */
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getReceiverOrBuilder();
  }
  /**
   * Protobuf type {@code Models.MthdInvc}
   */
  public  static final class MthdInvc extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.MthdInvc)
      MthdInvcOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MthdInvc.newBuilder() to construct.
    private MthdInvc(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MthdInvc() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MthdInvc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                arguments_ = com.google.protobuf.MapField.newMapField(
                    ArgumentsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id>
              arguments__ = input.readMessage(
                  ArgumentsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              arguments_.getMutableMap().put(
                  arguments__.getKey(), arguments__.getValue());
              break;
            }
            case 26: {
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = receiver_.toBuilder();
              }
              receiver_ = input.readMessage(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(receiver_);
                receiver_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.internal_static_Models_MthdInvc_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetArguments();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.internal_static_Models_MthdInvc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc.class, com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id id_;
    /**
     * <code>optional .Models.Id id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Models.Id id = 1;</code>
     */
    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getId() {
      return id_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : id_;
    }
    /**
     * <code>optional .Models.Id id = 1;</code>
     */
    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getIdOrBuilder() {
      return id_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : id_;
    }

    public static final int ARGUMENTS_FIELD_NUMBER = 2;
    private static final class ArgumentsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id>newDefaultInstance(
                  com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.internal_static_Models_MthdInvc_ArgumentsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> arguments_;
    private com.google.protobuf.MapField<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id>
    internalGetArguments() {
      if (arguments_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ArgumentsDefaultEntryHolder.defaultEntry);
      }
      return arguments_;
    }

    public int getArgumentsCount() {
      return internalGetArguments().getMap().size();
    }
    /**
     * <pre>
     * index -&gt; arg
     * </pre>
     *
     * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
     */

    public boolean containsArguments(
        int key) {
      
      return internalGetArguments().getMap().containsKey(key);
    }
    /**
     * Use {@link #getArgumentsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> getArguments() {
      return getArgumentsMap();
    }
    /**
     * <pre>
     * index -&gt; arg
     * </pre>
     *
     * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
     */

    public java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> getArgumentsMap() {
      return internalGetArguments().getMap();
    }
    /**
     * <pre>
     * index -&gt; arg
     * </pre>
     *
     * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
     */

    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getArgumentsOrDefault(
        int key,
        com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id defaultValue) {
      
      java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> map =
          internalGetArguments().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * index -&gt; arg
     * </pre>
     *
     * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
     */

    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getArgumentsOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> map =
          internalGetArguments().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int RECEIVER_FIELD_NUMBER = 3;
    private com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id receiver_;
    /**
     * <code>optional .Models.Id receiver = 3;</code>
     */
    public boolean hasReceiver() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Models.Id receiver = 3;</code>
     */
    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getReceiver() {
      return receiver_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : receiver_;
    }
    /**
     * <code>optional .Models.Id receiver = 3;</code>
     */
    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getReceiverOrBuilder() {
      return receiver_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : receiver_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getId());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetArguments(),
          ArgumentsDefaultEntryHolder.defaultEntry,
          2);
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(3, getReceiver());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      for (java.util.Map.Entry<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> entry
           : internalGetArguments().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id>
        arguments__ = ArgumentsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, arguments__);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getReceiver());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc)) {
        return super.equals(obj);
      }
      com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc other = (com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && internalGetArguments().equals(
          other.internalGetArguments());
      result = result && (hasReceiver() == other.hasReceiver());
      if (hasReceiver()) {
        result = result && getReceiver()
            .equals(other.getReceiver());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (!internalGetArguments().getMap().isEmpty()) {
        hash = (37 * hash) + ARGUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetArguments().hashCode();
      }
      if (hasReceiver()) {
        hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
        hash = (53 * hash) + getReceiver().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.MthdInvc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.MthdInvc)
        com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvcOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.internal_static_Models_MthdInvc_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetArguments();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableArguments();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.internal_static_Models_MthdInvc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc.class, com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc.Builder.class);
      }

      // Construct using MethodInvocation.MthdInvc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getIdFieldBuilder();
          getReceiverFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableArguments().clear();
        if (receiverBuilder_ == null) {
          receiver_ = null;
        } else {
          receiverBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.internal_static_Models_MthdInvc_descriptor;
      }

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc getDefaultInstanceForType() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc.getDefaultInstance();
      }

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc build() {
        com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc buildPartial() {
        com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc result = new com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        result.arguments_ = internalGetArguments();
        result.arguments_.makeImmutable();
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        if (receiverBuilder_ == null) {
          result.receiver_ = receiver_;
        } else {
          result.receiver_ = receiverBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc) {
          return mergeFrom((com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc other) {
        if (other == com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        internalGetMutableArguments().mergeFrom(
            other.internalGetArguments());
        if (other.hasReceiver()) {
          mergeReceiver(other.getReceiver());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id id_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder> idBuilder_;
      /**
       * <code>optional .Models.Id id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Models.Id id = 1;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getId() {
        if (idBuilder_ == null) {
          return id_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Models.Id id = 1;</code>
       */
      public Builder setId(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Models.Id id = 1;</code>
       */
      public Builder setId(
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Models.Id id = 1;</code>
       */
      public Builder mergeId(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              id_ != null &&
              id_ != com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance()) {
            id_ =
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Models.Id id = 1;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Models.Id id = 1;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder getIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Models.Id id = 1;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>optional .Models.Id id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> arguments_;
      private com.google.protobuf.MapField<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id>
      internalGetArguments() {
        if (arguments_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ArgumentsDefaultEntryHolder.defaultEntry);
        }
        return arguments_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id>
      internalGetMutableArguments() {
        onChanged();;
        if (arguments_ == null) {
          arguments_ = com.google.protobuf.MapField.newMapField(
              ArgumentsDefaultEntryHolder.defaultEntry);
        }
        if (!arguments_.isMutable()) {
          arguments_ = arguments_.copy();
        }
        return arguments_;
      }

      public int getArgumentsCount() {
        return internalGetArguments().getMap().size();
      }
      /**
       * <pre>
       * index -&gt; arg
       * </pre>
       *
       * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
       */

      public boolean containsArguments(
          int key) {
        
        return internalGetArguments().getMap().containsKey(key);
      }
      /**
       * Use {@link #getArgumentsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> getArguments() {
        return getArgumentsMap();
      }
      /**
       * <pre>
       * index -&gt; arg
       * </pre>
       *
       * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
       */

      public java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> getArgumentsMap() {
        return internalGetArguments().getMap();
      }
      /**
       * <pre>
       * index -&gt; arg
       * </pre>
       *
       * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
       */

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getArgumentsOrDefault(
          int key,
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id defaultValue) {
        
        java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> map =
            internalGetArguments().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * index -&gt; arg
       * </pre>
       *
       * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
       */

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getArgumentsOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> map =
            internalGetArguments().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearArguments() {
        internalGetMutableArguments().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * index -&gt; arg
       * </pre>
       *
       * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
       */

      public Builder removeArguments(
          int key) {
        
        internalGetMutableArguments().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id>
      getMutableArguments() {
        return internalGetMutableArguments().getMutableMap();
      }
      /**
       * <pre>
       * index -&gt; arg
       * </pre>
       *
       * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
       */
      public Builder putArguments(
          int key,
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableArguments().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * index -&gt; arg
       * </pre>
       *
       * <code>map&lt;int32, .Models.Id&gt; arguments = 2;</code>
       */

      public Builder putAllArguments(
          java.util.Map<java.lang.Integer, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id> values) {
        internalGetMutableArguments().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id receiver_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder> receiverBuilder_;
      /**
       * <code>optional .Models.Id receiver = 3;</code>
       */
      public boolean hasReceiver() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Models.Id receiver = 3;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getReceiver() {
        if (receiverBuilder_ == null) {
          return receiver_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : receiver_;
        } else {
          return receiverBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Models.Id receiver = 3;</code>
       */
      public Builder setReceiver(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id value) {
        if (receiverBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          receiver_ = value;
          onChanged();
        } else {
          receiverBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Models.Id receiver = 3;</code>
       */
      public Builder setReceiver(
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder builderForValue) {
        if (receiverBuilder_ == null) {
          receiver_ = builderForValue.build();
          onChanged();
        } else {
          receiverBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Models.Id receiver = 3;</code>
       */
      public Builder mergeReceiver(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id value) {
        if (receiverBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              receiver_ != null &&
              receiver_ != com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance()) {
            receiver_ =
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.newBuilder(receiver_).mergeFrom(value).buildPartial();
          } else {
            receiver_ = value;
          }
          onChanged();
        } else {
          receiverBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Models.Id receiver = 3;</code>
       */
      public Builder clearReceiver() {
        if (receiverBuilder_ == null) {
          receiver_ = null;
          onChanged();
        } else {
          receiverBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Models.Id receiver = 3;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder getReceiverBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getReceiverFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Models.Id receiver = 3;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getReceiverOrBuilder() {
        if (receiverBuilder_ != null) {
          return receiverBuilder_.getMessageOrBuilder();
        } else {
          return receiver_ == null ?
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : receiver_;
        }
      }
      /**
       * <code>optional .Models.Id receiver = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder> 
          getReceiverFieldBuilder() {
        if (receiverBuilder_ == null) {
          receiverBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder>(
                  getReceiver(),
                  getParentForChildren(),
                  isClean());
          receiver_ = null;
        }
        return receiverBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.MthdInvc)
    }

    // @@protoc_insertion_point(class_scope:Models.MthdInvc)
    private static final com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc();
    }

    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MthdInvc>
        PARSER = new com.google.protobuf.AbstractParser<MthdInvc>() {
      public MthdInvc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MthdInvc(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MthdInvc> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MthdInvc> getParserForType() {
      return PARSER;
    }

    public com.google.errorprone.bugpatterns.refactoringexperiment.models.MethodInvocation.MthdInvc getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_MthdInvc_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_MthdInvc_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_MthdInvc_ArgumentsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_MthdInvc_ArgumentsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MthdInvc.proto\022\006Models\032\024Identification" +
      ".proto\"\262\001\n\010MthdInvc\022\026\n\002id\030\001 \001(\0132\n.Models" +
      ".Id\0222\n\targuments\030\002 \003(\0132\037.Models.MthdInvc" +
      ".ArgumentsEntry\022\034\n\010receiver\030\003 \001(\0132\n.Mode" +
      "ls.Id\032<\n\016ArgumentsEntry\022\013\n\003key\030\001 \001(\005\022\031\n\005" +
      "value\030\002 \001(\0132\n.Models.Id:\0028\001BR\n>com.googl" +
      "e.errorprone.bugpatterns.refactoringexpe" +
      "riment.modelsB\020MethodInvocation"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.getDescriptor(),
        }, assigner);
    internal_static_Models_MthdInvc_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_MthdInvc_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_MthdInvc_descriptor,
        new java.lang.String[] { "Id", "Arguments", "Receiver", });
    internal_static_Models_MthdInvc_ArgumentsEntry_descriptor =
      internal_static_Models_MthdInvc_descriptor.getNestedTypes().get(0);
    internal_static_Models_MthdInvc_ArgumentsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_MthdInvc_ArgumentsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
