// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Return.proto

package com.google.errorprone.bugpatterns.refactoringexperiment.models;

public final class Return {
  private Return() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface rtrnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Models.rtrn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .Models.Id method_id = 1;</code>
     */
    boolean hasMethodId();
    /**
     * <code>optional .Models.Id method_id = 1;</code>
     */
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getMethodId();
    /**
     * <code>optional .Models.Id method_id = 1;</code>
     */
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getMethodIdOrBuilder();

    /**
     * <code>optional .Models.Id ret_expr = 2;</code>
     */
    boolean hasRetExpr();
    /**
     * <code>optional .Models.Id ret_expr = 2;</code>
     */
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getRetExpr();
    /**
     * <code>optional .Models.Id ret_expr = 2;</code>
     */
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getRetExprOrBuilder();
  }
  /**
   * Protobuf type {@code Models.rtrn}
   */
  public  static final class rtrn extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Models.rtrn)
      rtrnOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use rtrn.newBuilder() to construct.
    private rtrn(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private rtrn() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private rtrn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = methodId_.toBuilder();
              }
              methodId_ = input.readMessage(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(methodId_);
                methodId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = retExpr_.toBuilder();
              }
              retExpr_ = input.readMessage(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(retExpr_);
                retExpr_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.internal_static_Models_rtrn_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.internal_static_Models_rtrn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn.class, com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn.Builder.class);
    }

    private int bitField0_;
    public static final int METHOD_ID_FIELD_NUMBER = 1;
    private com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id methodId_;
    /**
     * <code>optional .Models.Id method_id = 1;</code>
     */
    public boolean hasMethodId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Models.Id method_id = 1;</code>
     */
    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getMethodId() {
      return methodId_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : methodId_;
    }
    /**
     * <code>optional .Models.Id method_id = 1;</code>
     */
    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getMethodIdOrBuilder() {
      return methodId_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : methodId_;
    }

    public static final int RET_EXPR_FIELD_NUMBER = 2;
    private com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id retExpr_;
    /**
     * <code>optional .Models.Id ret_expr = 2;</code>
     */
    public boolean hasRetExpr() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Models.Id ret_expr = 2;</code>
     */
    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getRetExpr() {
      return retExpr_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : retExpr_;
    }
    /**
     * <code>optional .Models.Id ret_expr = 2;</code>
     */
    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getRetExprOrBuilder() {
      return retExpr_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : retExpr_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getMethodId());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getRetExpr());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMethodId());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRetExpr());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn)) {
        return super.equals(obj);
      }
      com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn other = (com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn) obj;

      boolean result = true;
      result = result && (hasMethodId() == other.hasMethodId());
      if (hasMethodId()) {
        result = result && getMethodId()
            .equals(other.getMethodId());
      }
      result = result && (hasRetExpr() == other.hasRetExpr());
      if (hasRetExpr()) {
        result = result && getRetExpr()
            .equals(other.getRetExpr());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMethodId()) {
        hash = (37 * hash) + METHOD_ID_FIELD_NUMBER;
        hash = (53 * hash) + getMethodId().hashCode();
      }
      if (hasRetExpr()) {
        hash = (37 * hash) + RET_EXPR_FIELD_NUMBER;
        hash = (53 * hash) + getRetExpr().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Models.rtrn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Models.rtrn)
        com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.internal_static_Models_rtrn_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.internal_static_Models_rtrn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn.class, com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn.Builder.class);
      }

      // Construct using Return.rtrn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMethodIdFieldBuilder();
          getRetExprFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (methodIdBuilder_ == null) {
          methodId_ = null;
        } else {
          methodIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (retExprBuilder_ == null) {
          retExpr_ = null;
        } else {
          retExprBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.internal_static_Models_rtrn_descriptor;
      }

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn getDefaultInstanceForType() {
        return com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn.getDefaultInstance();
      }

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn build() {
        com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn buildPartial() {
        com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn result = new com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (methodIdBuilder_ == null) {
          result.methodId_ = methodId_;
        } else {
          result.methodId_ = methodIdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (retExprBuilder_ == null) {
          result.retExpr_ = retExpr_;
        } else {
          result.retExpr_ = retExprBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn) {
          return mergeFrom((com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn other) {
        if (other == com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn.getDefaultInstance()) return this;
        if (other.hasMethodId()) {
          mergeMethodId(other.getMethodId());
        }
        if (other.hasRetExpr()) {
          mergeRetExpr(other.getRetExpr());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id methodId_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder> methodIdBuilder_;
      /**
       * <code>optional .Models.Id method_id = 1;</code>
       */
      public boolean hasMethodId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Models.Id method_id = 1;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getMethodId() {
        if (methodIdBuilder_ == null) {
          return methodId_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : methodId_;
        } else {
          return methodIdBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Models.Id method_id = 1;</code>
       */
      public Builder setMethodId(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id value) {
        if (methodIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          methodId_ = value;
          onChanged();
        } else {
          methodIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Models.Id method_id = 1;</code>
       */
      public Builder setMethodId(
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder builderForValue) {
        if (methodIdBuilder_ == null) {
          methodId_ = builderForValue.build();
          onChanged();
        } else {
          methodIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Models.Id method_id = 1;</code>
       */
      public Builder mergeMethodId(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id value) {
        if (methodIdBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              methodId_ != null &&
              methodId_ != com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance()) {
            methodId_ =
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.newBuilder(methodId_).mergeFrom(value).buildPartial();
          } else {
            methodId_ = value;
          }
          onChanged();
        } else {
          methodIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .Models.Id method_id = 1;</code>
       */
      public Builder clearMethodId() {
        if (methodIdBuilder_ == null) {
          methodId_ = null;
          onChanged();
        } else {
          methodIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .Models.Id method_id = 1;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder getMethodIdBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMethodIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Models.Id method_id = 1;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getMethodIdOrBuilder() {
        if (methodIdBuilder_ != null) {
          return methodIdBuilder_.getMessageOrBuilder();
        } else {
          return methodId_ == null ?
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : methodId_;
        }
      }
      /**
       * <code>optional .Models.Id method_id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder> 
          getMethodIdFieldBuilder() {
        if (methodIdBuilder_ == null) {
          methodIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder>(
                  getMethodId(),
                  getParentForChildren(),
                  isClean());
          methodId_ = null;
        }
        return methodIdBuilder_;
      }

      private com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id retExpr_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder> retExprBuilder_;
      /**
       * <code>optional .Models.Id ret_expr = 2;</code>
       */
      public boolean hasRetExpr() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .Models.Id ret_expr = 2;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id getRetExpr() {
        if (retExprBuilder_ == null) {
          return retExpr_ == null ? com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : retExpr_;
        } else {
          return retExprBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Models.Id ret_expr = 2;</code>
       */
      public Builder setRetExpr(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id value) {
        if (retExprBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          retExpr_ = value;
          onChanged();
        } else {
          retExprBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Models.Id ret_expr = 2;</code>
       */
      public Builder setRetExpr(
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder builderForValue) {
        if (retExprBuilder_ == null) {
          retExpr_ = builderForValue.build();
          onChanged();
        } else {
          retExprBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Models.Id ret_expr = 2;</code>
       */
      public Builder mergeRetExpr(com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id value) {
        if (retExprBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              retExpr_ != null &&
              retExpr_ != com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance()) {
            retExpr_ =
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.newBuilder(retExpr_).mergeFrom(value).buildPartial();
          } else {
            retExpr_ = value;
          }
          onChanged();
        } else {
          retExprBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .Models.Id ret_expr = 2;</code>
       */
      public Builder clearRetExpr() {
        if (retExprBuilder_ == null) {
          retExpr_ = null;
          onChanged();
        } else {
          retExprBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .Models.Id ret_expr = 2;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder getRetExprBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRetExprFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Models.Id ret_expr = 2;</code>
       */
      public com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder getRetExprOrBuilder() {
        if (retExprBuilder_ != null) {
          return retExprBuilder_.getMessageOrBuilder();
        } else {
          return retExpr_ == null ?
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.getDefaultInstance() : retExpr_;
        }
      }
      /**
       * <code>optional .Models.Id ret_expr = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder> 
          getRetExprFieldBuilder() {
        if (retExprBuilder_ == null) {
          retExprBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.Id.Builder, com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.IdOrBuilder>(
                  getRetExpr(),
                  getParentForChildren(),
                  isClean());
          retExpr_ = null;
        }
        return retExprBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Models.rtrn)
    }

    // @@protoc_insertion_point(class_scope:Models.rtrn)
    private static final com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn();
    }

    public static com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<rtrn>
        PARSER = new com.google.protobuf.AbstractParser<rtrn>() {
      public rtrn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new rtrn(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<rtrn> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<rtrn> getParserForType() {
      return PARSER;
    }

    public com.google.errorprone.bugpatterns.refactoringexperiment.models.Return.rtrn getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Models_rtrn_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Models_rtrn_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Return.proto\022\006Models\032\024Identification.p" +
      "roto\"C\n\004rtrn\022\035\n\tmethod_id\030\001 \001(\0132\n.Models" +
      ".Id\022\034\n\010ret_expr\030\002 \001(\0132\n.Models.IdBH\n>com" +
      ".google.errorprone.bugpatterns.refactori" +
      "ngexperiment.modelsB\006Return"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.getDescriptor(),
        }, assigner);
    internal_static_Models_rtrn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Models_rtrn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Models_rtrn_descriptor,
        new java.lang.String[] { "MethodId", "RetExpr", });
    com.google.errorprone.bugpatterns.refactoringexperiment.models.Identification.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
