# Description:
#   Error prone is a library for matching Javac ASTs, and detecting common
#   Java programming mistakes.

package(default_visibility = ["//visibility:public"])

licenses(["notice"])  # Apache 2.0

java_library(
    name = "annotation",
    srcs = glob(["src/main/java/**/*.java"]),
)
